model_name: MedMamba
ckpt_path: E:/Studies/Thesis/Mamba/Windows/MedMamba/models
history_path: E:/Studies/Thesis/Mamba/Windows/MedMamba/evaluation
train_data_path: E:/Studies/Thesis/Mamba/Windows/MedMamba/data/train/
val_data_path: E:/Studies/Thesis/Mamba/Windows/MedMamba/data/val/
test_data_path: E:/Studies/Thesis/Mamba/Windows/MedMamba/data/test/
image_size: 128
classes: 6